const GET_ITEMS = 'GET_ITEMS'
const SEND_ITEM = 'SEND_ITEM'
const DELETE_ITEM = 'DELETE_ITEM'
const ITEMS_LOADING = 'ITEMS_LOADING'
export {
    GET_ITEMS,
    SEND_ITEM,
    DELETE_ITEM,
    ITEMS_LOADING
}